// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerAPI.Models.Context;

#nullable disable

namespace ServerAPI.Migrations.HocSinhDB
{
    [DbContext(typeof(HocSinhDBContext))]
    [Migration("20230517041233_DbHocSinh")]
    partial class DbHocSinh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ServerAPI.Models.HocSinh.HocSinh", b =>
                {
                    b.Property<int>("MaHS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHS"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LopMaLop")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<int>("TenHS")
                        .HasColumnType("int");

                    b.Property<int>("TuoiHS")
                        .HasColumnType("int");

                    b.HasKey("MaHS");

                    b.HasIndex("LopMaLop");

                    b.ToTable("HocSinhs");
                });

            modelBuilder.Entity("ServerAPI.Models.HocSinh.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"), 1L, 1);

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLop");

                    b.ToTable("Lops");
                });

            modelBuilder.Entity("ServerAPI.Models.HocSinh.MonHoc", b =>
                {
                    b.Property<int>("MaMH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMH"), 1L, 1);

                    b.Property<double>("DiemSo")
                        .HasColumnType("float");

                    b.Property<int?>("HocSinhMaHS")
                        .HasColumnType("int");

                    b.Property<string>("TenMH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMH");

                    b.HasIndex("HocSinhMaHS");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("ServerAPI.Models.HocSinh.HocSinh", b =>
                {
                    b.HasOne("ServerAPI.Models.HocSinh.Lop", null)
                        .WithMany("HocSinh")
                        .HasForeignKey("LopMaLop");
                });

            modelBuilder.Entity("ServerAPI.Models.HocSinh.MonHoc", b =>
                {
                    b.HasOne("ServerAPI.Models.HocSinh.HocSinh", null)
                        .WithMany("MonHocs")
                        .HasForeignKey("HocSinhMaHS");
                });

            modelBuilder.Entity("ServerAPI.Models.HocSinh.HocSinh", b =>
                {
                    b.Navigation("MonHocs");
                });

            modelBuilder.Entity("ServerAPI.Models.HocSinh.Lop", b =>
                {
                    b.Navigation("HocSinh");
                });
#pragma warning restore 612, 618
        }
    }
}
